version: '{build}'
os: Windows Server 2012
environment:
  ANDROID_HOME: "C:\\android"
init:
  - mkdir "%ANDROID_HOME%"
  - cd "%ANDROID_HOME%"
  - appveyor DownloadFile "https://dl.google.com/android/repository/tools_r25.2.3-windows.zip"
  - 7z x "tools_r25.2.3-windows.zip" > nul
  - cd "C:\projects\Remote"
install:
  - echo y | "%ANDROID_HOME%\tools\android.bat" --silent update sdk --no-ui --all --filter platform-tools,tools,build-tools-26.0.2,android-26,android-25,extras-google-m2repository,extras-android-m2repository
  - ps: for($i=0;$i -lt 30;$i++) { $response += "y`n"}; $response | cmd /c 'C:\android\tools\bin\sdkmanager.bat 2>&1' --update
build_script:
  - mvn clean install --batch-mode -DskipTest