version: '{build}'
os: Windows Server 2012
environment:
   ANDROID_HOME: "C:\\android-sdk-windows"
   ANDROID_TOOLS_URL: "https://dl.google.com/android/repository/tools_r25.2.3-windows.zip"
init:
  - mkdir "%ANDROID_HOME%"
  - cd "%ANDROID_HOME%"
  - appveyor DownloadFile "https://dl.google.com/android/repository/tools_r25.2.3-windows.zip"
  - 7z x "tools_r25.2.3-windows.zip" > nul
  - cd "C:\projects\Remote"
install:
  - mkdir %ANDROID_HOME%\licenses
  - ps: 'Add-Content -Value "`n8933bad161af4178b1185d1a37fbf41ea5269c55`n`nd56f5187479451eabf01fb78af6dfcb131a6481e" -Path $env:ANDROID_HOME\licenses\android-sdk-license -Encoding ASCII'
  - ps: 'Add-Content -Value "`n84831b9409646a918e30573bab4c9c91346d8abd`n504667f4c0de7af1a06de9f4b1727b84351f2910" -Path $env:ANDROID_HOME\licenses\android-sdk-preview-license -Encoding ASCII'
  - '%ANDROID_HOME%\tools\bin\sdkmanager.bat tools'
  - '%ANDROID_HOME%\tools\bin\sdkmanager.bat platform-tools'
  - '%ANDROID_HOME%\tools\bin\sdkmanager.bat build-tools;26.0.2'
  - '%ANDROID_HOME%\tools\bin\sdkmanager.bat platforms;android-26'
  - '%ANDROID_HOME%\tools\bin\sdkmanager.bat extras;android;m2repository'
build_script:
  - mvn clean install --batch-mode -DskipTest