version: '{build}'
os: Windows Server 2012
install:
  - cmd: SET ANDROID_HOME=C:\Program Files (x86)\Android\android-sdk
  - mkdir -p "%ANDROID_HOME%/licenses"
  - echo. >> "%ANDROID_HOME%/licenses/android-sdk-license"
  - echo 8933bad161af4178b1185d1a37fbf41ea5269c55 >> "%ANDROID_HOME%/licenses/android-sdk-license"
  - echo. >> "%ANDROID_HOME%/licenses/android-sdk-license"
  - echo d56f5187479451eabf01fb78af6dfcb131a6481e >> "%ANDROID_HOME%/licenses/android-sdk-license"
build_script:
  - mvn clean package --batch-mode -DskipTest
test_script:
  - mvn clean install --batch-mode