version: '{build}'
os: Windows Server 2012
install:
  - cmd: SET ANDROID_HOME=C:\Program Files (x86)\Android\android-sdk
build_script:
  - mvn clean package --batch-mode -DskipTest
test_script:
  - mvn clean install --batch-mode